In [11]:
import pandas as pd
import os
import epiweeks

In [43]:
files = os.listdir("../raw/multistrain_retrospective_trajectories/")
#files = ['trajectories_aggregated_202608.csv']#, 'trajectories_aggregated_202607.csv']
all_data = []
for file in files:
    if file[0] == ".":
        continue

    df = pd.read_csv("../raw/multistrain_retrospective_trajectories/%s" % file)
    df['date'] = pd.to_datetime(df['date'])
    file_horizon0 = file.split("_")[-1].split(".")[0]
    df['reference_date'] = pd.to_datetime(epiweeks.Week.fromstring(file_horizon0).enddate())    
    df_filter = df[df.date>=df.reference_date]
    df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
    df_filter.rename(columns={"location":"location_name_epydemix"})
    df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())

    df_filter = df_filter[df_filter.horizon<=3]

    df_filter.to_parquet("../raw/multistrain_retrospective_trajectories/%s" % "epystrain_trajectories_%s.parquet" % pd.to_datetime(epiweeks.Week.fromstring(file_horizon0).enddate()).strftime("%Y-%m-%d"), index = False)
    #all_data.append(df_filter) 
    
#df_final = pd.concat(all_data)

/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['horizon'] = (df_filter['date'] - df_filter['reference_date']).dt.days//7
/var/folders/pz/_0b3g5n54ys25g7dz01fkx6h0000gp/T/ipykernel_77230/3661292691.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_filter['epiweek'] = df_filter['date'].apply(lambda x: epiweeks.Week.fromdate(x).cdcformat())

In [41]:
file

'.DS_Store'

In [44]:
df_filter

,sample_id,sim_id_h1,sim_id_h3,sim_id_b,location,date,target_h1,target_h3,target_b,target_total,reference_date,horizon,epiweek
10,264,771,371,0,United_States,2025-11-29,780.0,6149.0,213.0,7142.0,2025-11-29,0,202548
11,264,771,371,0,United_States,2025-12-06,1160.0,12227.0,312.0,13699.0,2025-11-29,1,202549
12,264,771,371,0,United_States,2025-12-13,2020.0,25918.0,474.0,28412.0,2025-11-29,2,202550
13,264,771,371,0,United_States,2025-12-20,3771.0,58996.0,863.0,63630.0,2025-11-29,3,202551
45,264,771,371,0,United_States_Alabama,2025-11-29,9.0,40.0,1.0,50.0,2025-11-29,0,202548
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1819943,529,474,482,999,United_States_Wisconsin,2025-12-20,0.0,52.0,0.0,52.0,2025-11-29,3,202551
1819975,529,474,482,999,United_States_Wyoming,2025-11-29,0.0,2.0,0.0,2.0,2025-11-29,0,202548
1819976,529,474,482,999,United_States_Wyoming,2025-12-06,0.0,2.0,2.0,4.0,2025-11-29,1,202549
1819977,529,474,482,999,United_States_Wyoming,2025-12-13,0.0,2.0,1.0,3.0,2025-11-29,2,202550
1819978,529,474,482,999,United_States_Wyoming,2025-12-20,0.0,2.0,1.0,3.0,2025-11-29,3,202551

In [38]:
df_filter

,sample_id,sim_id_h1,sim_id_h3,sim_id_b,location,date,target_h1,target_h3,target_b,target_total,reference_date,horizon,epiweek
23,264,771,371,0,United_States,2026-02-28,911.0,2514.0,3107.0,6532.0,2026-02-28,0,202608
24,264,771,371,0,United_States,2026-03-07,549.0,1027.0,2326.0,3902.0,2026-02-28,1,202609
25,264,771,371,0,United_States,2026-03-14,338.0,394.0,1788.0,2520.0,2026-02-28,2,202610
26,264,771,371,0,United_States,2026-03-21,150.0,145.0,1247.0,1542.0,2026-02-28,3,202611
27,264,771,371,0,United_States,2026-03-28,69.0,51.0,854.0,974.0,2026-02-28,4,202612
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1819995,529,474,482,999,United_States_Wyoming,2026-04-18,0.0,0.0,1.0,1.0,2026-02-28,7,202615
1819996,529,474,482,999,United_States_Wyoming,2026-04-25,0.0,0.0,0.0,0.0,2026-02-28,8,202616
1819997,529,474,482,999,United_States_Wyoming,2026-05-02,0.0,0.0,1.0,1.0,2026-02-28,9,202617
1819998,529,474,482,999,United_States_Wyoming,2026-05-09,0.0,0.0,0.0,0.0,2026-02-28,10,202618
1819999,529,474,482,999,United_States_Wyoming,2026-05-16,0.0,0.0,1.0,1.0,2026-02-28,11,202619